# Generated by Django 3.1 on 2020-08-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20200807_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadosData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='name')),
                ('cases', models.PositiveIntegerField(default=0, verbose_name='cases')),
                ('deaths', models.PositiveIntegerField(default=0, verbose_name='deaths')),
            ],
        ),
        migrations.CreateModel(
            name='RegiaoData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='name')),
                ('cases', models.PositiveIntegerField(default=0, verbose_name='cases')),
                ('deaths', models.PositiveIntegerField(default=0, verbose_name='deaths')),
            ],
        ),
    ]
